apiVersion: v1
kind: Secret
metadata:
 name: api-usermng-secrets
 namespace: realestate
type: Opaque
data:
 # Replace these base64-encoded values with real ones (or create secret with kubectl create secret)
 # Example: echo -n 'mongodb://user:pass@host:27017/db' | base64
 mongodb-uri: bW9uZ29kYitzcnY6Ly9hZG1pbjpmUlJ4M0lzdzY0eFdKVVB4QGNsdXN0ZXIwLmdndWx4dTUubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXIw
 jwt-access-secret: Y2hhbmdlLXRoaXMtc2VjcmV0
 jwt-refresh-secret: c2RYTjBaWEl3TG1kbmRXeDRkVFV1Ylc5dVoy
 smtp-password: U0B1cHBvcnQhMTk4MjM=
 redis-host: MTQ4LjIzMC4xMTIuMTQ4
 redis-port: NjM3OQ==
 redis-username: aHNhc3Nh
 redis-password: QWJjZEAxOTg0
 redis-db: MA==