apiVersion: v1
kind: Service
metadata:
  name: api-auth-service
  namespace: realestate
  labels:
    app: api-auth
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3001
    nodePort: 30001  # Port permanent accessible depuis l'ext√©rieur
    protocol: TCP
    name: http
  selector:
    app: api-auth