apiVersion: v1
kind: Service
metadata:
  name: api-auth
  namespace: realestate
  labels:
    app: api-auth
spec:
  type: ClusterIP
  selector:
    app: api-auth
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
 name: api-usermng
 namespace: realestate
 labels:
   app: api-usermng
spec:
 type: ClusterIP
 selector:
   app: api-usermng
 ports:
   - name: http
     port: 3002
     targetPort: 3002
     protocol: TCP