apiVersion: v1
kind: Service
metadata:
  name: api-auth
  namespace: realestate
  labels:
    app: api-auth
spec:
  type: ClusterIP
  selector:
    app: api-auth
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP